default_language_version:
  python: python3.10

repos:
  - repo: local
    hooks:
      - id: pre-push
        name: pre-push
        stages: [pre-push]
        entry: |
          echo "Executing pre-push hook"
          git rebase -i --root
        language: system
        always_run: true
