default_language_version:
  python: python3.10

repos:
  - repo: local
    hooks:
      - id: post-commit
        name: post-commit
        stages: [post-commit]
        entry: |
          echo "Executing pre-push hook"
          git rebase -i --root
        language: system
        always_run: true
