default_language_version:
  python: python3.10

repos:
  - repo: local
    hooks:
      - id: commit-msg
        name: commit-msg
        entry: echo "Executing commit-msg hook"
        language: system
        always_run: true
