default_language_version:
  python: python3.10

repos:
  - repo: local
    hooks:
      - id: pre-commit
        name: pre-commit
        stages: [ post-commit ]
        entry: git rebase -i --root
        language: system
        always_run: true
